export { ResourcesListPage } from './ResourcesListPage'
export { ResourceOverviewPage } from './ResourceOverviewPage'
export { ResourceDetailsPage } from './ResourceDetailsPage'
export { BasicInfoPage } from './BasicInfoPage'
export { ProjectDetailsPage } from './ProjectDetailsPage'
